apiVersion: v1
kind: Service
metadata:
  name: goapp
  namespace: ashwani
  labels:
    app: goapp
spec:
  type: NodePort
  ports:
  - port: 6379
    protocol: TCP
    targetPort: goappport
  selector:
    name: goapp