apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp
  namespace: demo-ops
  labels:
    name: goapp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: goapp
  template:
    metadata:
      labels:
        name: goapp
    spec:
      containers:
      - name: goapp
        image: imaskm/zero:latest 
        imagePullPolicy: Always
        ports:
          - containerPort: 8000
            name: goappport
        env:
        - name: REDIS_DEMO_ADDR
          value: "redis:6379"
        - name: APP_DEMO_ADDR
          value: "0.0.0.0:8000"
        resources:
          requests:
            cpu: 250m
            memory: 20Mi 
        command:

        livenessProbe:
          exec: 
            command:
              - netstat -plant | grep "8000"
            path: ''
            port: 8000
        

    
        