apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: demo-ops
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
    protocol: TCP
    targetPort: redisport
  selector:
    name: redis