apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: demo-ops
  labels:
    name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis
  template:
    metadata:
      labels:
        name: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        imagePullPolicy: Always
        command:
        - redis-server  
        - "--appendonly yes"
        volumeMounts:
        - mountPath: /data
          name: data  
        ports:
          - containerPort: 6379
            name: redisport 
      volumes:
      - name: data
        hostPath:
          path: /data
          type: DirectoryOrCreate
        
